<?php

use Illuminate\Database\Seeder;
use App\Food;

class FoodSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Food::insert([
            //1
            [
                'name' => 'ข้าวกะเพราไก่',
                'description' => 'ไก่',
                'image_url' => '/images/foods/t.jpg',
                'is_recommend' => 1,
                'price' => 40.00,
                'discount' => 5,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวกะเพราหมู',
                'description' => 'ไก่',
                'image_url' => '/images/foods/kapraomoo.png',
                'is_recommend' => 1,
                'price' => 40.00,
                'discount' => 5,
                'category_id' => 2,
            ],
            [
                'name' => 'ข้าวกะเพราหมูกรอบ',
                'description' => 'หมูกรอบ',
                'image_url' => '/images/foods/kapraomookrop.png',
                'is_recommend' => 1,
                'price' => 45.00,
                'discount' => 5,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวกะเพราเนื้อ',
                'description' => 'เนื้อ',
                'image_url' => '/images/foods/kapronue.png',
                'is_recommend' => 1,
                'price' => 45.00,
                'discount' => 5,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวกะเพรากุ้ง',
                'description' => 'กุ้ง',
                'image_url' => '/images/foods/kaprokung.png',
                'is_recommend' => 1,
                'price' => 50.00,
                'discount' => 5,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวไก่กระเทียม',
                'description' => 'ไก่',
                'image_url' => '/images/foods/kaikrateam.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวหมูกระเทียม',
                'description' => 'หมู',
                'image_url' => '/images/foods/mookrateam.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวหมูกรอบกระเทียม',
                'description' => 'หมูกรอบ',
                'image_url' => '/images/foods/mookropkrateam.png',
                'is_recommend' => 0,
                'price' => 45.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวเนื้อกระเทียม',
                'description' => 'เนื้อ',
                'image_url' => '/images/foods/nuekrateam.png',
                'is_recommend' => 0,
                'price' => 45.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวกุ้งกระเทียม',
                'description' => 'กุ้ง',
                'image_url' => '/images/foods/krungkrateam.png',
                'is_recommend' => 0,
                'price' => 50.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวพริกเผาไก่',
                'description' => 'ไก่',
                'image_url' => '/images/foods/prikpaokai.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวพริกเผาหมู',
                'description' => 'หมู',
                'image_url' => '/images/foods/prikpaomoo.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวพริกเผาหมูกรอบ',
                'description' => 'หมูกรอบ',
                'image_url' => '/images/foods/prikpaomookrop.png',
                'is_recommend' => 0,
                'price' => 45.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวพริกเผาเนื้อ',
                'description' => 'เนื้อ',
                'image_url' => '/images/foods/prikpaonue.png',
                'is_recommend' => 0,
                'price' => 45.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวพริกเผากุ้ง',
                'description' => 'กุ้ง',
                'image_url' => '/images/foods/prikpaokung.png',
                'is_recommend' => 0,
                'price' => 50.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวพริกแกงไก่',
                'description' => 'ไก่',
                'image_url' => '/images/foods/prikkangkai.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวพริกแกงหมู',
                'description' => 'หมู',
                'image_url' => '/images/foods/prikkangmoo.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวพริกแกงหมูกรอบ',
                'description' => 'หมูกรอบ',
                'image_url' => '/images/foods/prikkangmookrop.png',
                'is_recommend' => 0,
                'price' => 45.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวพริกแกงเนื้อ',
                'description' => 'เนื้อ',
                'image_url' => '/images/foods/prikkangnue.png',
                'is_recommend' => 0,
                'price' => 45.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวพริกแกงกุ้ง',
                'description' => 'กุ้ง',
                'image_url' => '/images/foods/prikkangkung.png',
                'is_recommend' => 0,
                'price' => 50.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวพริกสดไก่',
                'description' => 'ไก่',
                'image_url' => '/images/foods/priksodkai.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวพริกสดหมู',
                'description' => 'หมู',
                'image_url' => '/images/foods/priksodmoo.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวพริกสดหมูกรอบ',
                'description' => 'หมูกรอบ',
                'image_url' => '/images/foods/priksodmookrop.png',
                'is_recommend' => 0,
                'price' => 45.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวพริกสดเนื้อ',
                'description' => 'เนื้อ',
                'image_url' => '/images/foods/priksodnue.png',
                'is_recommend' => 0,
                'price' => 45.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวพริกสดกุ้ง',
                'description' => 'กุ้ง',
                'image_url' => '/images/foods/priksodkung.png',
                'is_recommend' => 0,
                'price' => 50.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวผัดไก่',
                'description' => 'ไก่',
                'image_url' => '/images/foods/kaopadkai.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวผัดหมู',
                'description' => 'หมู',
                'image_url' => '/images/foods/kaopadmoo.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวผัดหมูกรอบ',
                'description' => 'หมูกรอบ',
                'image_url' => '/images/foods/kaopadmookrop.png',
                'is_recommend' => 0,
                'price' => 45.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวผัดเนื้อ',
                'description' => 'เนื้อ',
                'image_url' => '/images/foods/kaopadnue.png',
                'is_recommend' => 0,
                'price' => 45.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวผัดกุ้ง',
                'description' => 'กุ้ง',
                'image_url' => '/images/foods/kaopadkung.png',
                'is_recommend' => 0,
                'price' => 50.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวเขียวหวานไก่',
                'description' => 'ไก่',
                'image_url' => '/images/foods/keowwankai.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวเขียวหวานหมู',
                'description' => 'หมู',
                'image_url' => '/images/foods/keowwanmoo.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวเขียวหวานหมูกรอบ',
                'description' => 'หมูกรอบ',
                'image_url' => '/images/foods/keowwanmookrop.png',
                'is_recommend' => 0,
                'price' => 45.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวเขียวหวานเนื้อ',
                'description' => 'เนื้อ',
                'image_url' => '/images/foods/keowwannue.png',
                'is_recommend' => 0,
                'price' => 45.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวเขียวหวานกุ้ง',
                'description' => 'กุ้ง',
                'image_url' => '/images/foods/keowwankung.png',
                'is_recommend' => 0,
                'price' => 50.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวพะแนงไก่',
                'description' => 'ไก่',
                'image_url' => '/images/foods/panangkai.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวพะแนงหมู',
                'description' => 'หมู',
                'image_url' => '/images/foods/panangmoo.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวพะแนงหมูกรอบ',
                'description' => 'หมูกรอบ',
                'image_url' => '/images/foods/panangmookrop.png',
                'is_recommend' => 0,
                'price' => 45.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวพะแนงเนื้อ',
                'description' => 'เนื้อ',
                'image_url' => '/images/foods/panangnue.png',
                'is_recommend' => 0,
                'price' => 45.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวพะแนงกุ้ง',
                'description' => 'กุ้ง',
                'image_url' => '/images/foods/panangkung.png',
                'is_recommend' => 0,
                'price' => 50.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวผัดขี้เมาไก่',
                'description' => 'ไก่',
                'image_url' => '/images/foods/keemaokai.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวผัดขี้เมาหมู',
                'description' => 'หมู',
                'image_url' => '/images/foods/keemaomoo.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวผัดขี้เมาหมูกรอบ',
                'description' => 'หมูกรอบ',
                'image_url' => '/images/foods/keemaomookrop.png',
                'is_recommend' => 0,
                'price' => 45.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวผัดขี้เมาเนื้อ',
                'description' => 'เนื้อ',
                'image_url' => '/images/foods/keemaonue.png',
                'is_recommend' => 0,
                'price' => 45.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวผัดขี้เมากุ้ง',
                'description' => 'กุ้ง',
                'image_url' => '/images/foods/keemaokung.png',
                'is_recommend' => 0,
                'price' => 50.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ผัดมาม่าไก่',
                'description' => 'ไก่',
                'image_url' => '/images/foods/padmamakai.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ผัดมาม่าหมู',
                'description' => 'หมู',
                'image_url' => '/images/foods/padmamamoo.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ผัดมาม่าหมูกรอบ',
                'description' => 'หมูกรอบ',
                'image_url' => '/images/foods/padmamamookrop.png',
                'is_recommend' => 0,
                'price' => 45.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ผัดมาม่าเนื้อ',
                'description' => 'เนื้อ',
                'image_url' => '/images/foods/padmamanue.png',
                'is_recommend' => 0,
                'price' => 45.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ผัดมาม่ากุ้ง',
                'description' => 'กุ้ง',
                'image_url' => '/images/foods/padmamakung.png',
                'is_recommend' => 0,
                'price' => 50.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวกะหรี่ไก่',
                'description' => 'ไก่',
                'image_url' => '/images/foods/krareekai.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวกะหรี่หมู',
                'description' => 'หมู',
                'image_url' => '/images/foods/krareemoo.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวกะหรี่หมูกรอบ',
                'description' => 'หมูกรอบ',
                'image_url' => '/images/foods/krareemookrop.png',
                'is_recommend' => 0,
                'price' => 45.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวกะหรี่เนื้อ',
                'description' => 'เนื้อ',
                'image_url' => '/images/foods/krareenue.png',
                'is_recommend' => 0,
                'price' => 45.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวกะหรี่กุ้ง',
                'description' => 'กุ้ง',
                'image_url' => '/images/foods/krareekung.png',
                'is_recommend' => 0,
                'price' => 50.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ยำไข่ดาว',
                'description' => 'ไข่ดาว',
                'image_url' => '/images/foods/yumkaidown.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 2,
            ],

            [
                'name' => 'ยำกุนเชียง',
                'description' => 'กุนเชียง',
                'image_url' => '/images/foods/yumkuncheing.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 2,
            ],
            [
                'name' => 'ยำหมูมะนาว',
                'description' => 'หมู',
                'image_url' => '/images/foods/yummoomanow.png',
                'is_recommend' => 0,
                'price' => 50.00,
                'discount' => 0,
                'category_id' => 2,
            ],
            [
                'name' => 'ยำหมูกรอบ',
                'description' => 'หมูกรอบ',
                'image_url' => '/images/foods/yummookrop.png',
                'is_recommend' => 0,
                'price' => 50.00,
                'discount' => 0,
                'category_id' => 2,
            ],
            [
                'name' => 'ต้มยำไก่',
                'description' => 'ไก่',
                'image_url' => '/images/foods/tomyumkai.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 3,
            ],
            [
                'name' => 'ต้มยำกุ้ง',
                'description' => 'กุ้ง',
                'image_url' => '/images/foods/tomyumkung.png',
                'is_recommend' => 0,
                'price' => 60.00,
                'discount' => 0,
                'category_id' => 3,
            ],
            [
                'name' => 'ต้มยำหมู',
                'description' => 'หมู',
                'image_url' => '/images/foods/tomyummoo.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 3,
            ],
            [
                'name' => 'พิซซ่าค็อตโต้',
                'description' => 'พิซซ่าแฮม_มะกอกดำ_ไข่ต้ม_มะเขือเทศ_ชีส',
                'image_url' => '/images/foods/pizza_al_quattro.png',
                'is_recommend' => 0,
                'price' => 169.00,
                'discount' => 0,
                'category_id' => 5,
            ],
            [
                'name' => 'พิซซ่าคาลาซิงก้า',
                'description' => 'พิซซ่าซาลามี_หอมใหญ่_พริกใหญ่_มะเขือเทศ_ชีส',
                'image_url' => '/images/foods/pizza_casalinga.png',
                'is_recommend' => 0,
                'price' => 169.00,
                'discount' => 0,
                'category_id' => 5,
            ],
            [
                'name' => 'เสต็กเนื้อรสพริกไทย',
                'description' => 'เสต็ก_เนื้อ_พริกไทยดำ',
                'image_url' => '/images/foods/pepper_streak_breef.png',
                'is_recommend' => 0,
                'price' => 169.00,
                'discount' => 0,
                'category_id' => 6,
            ],
            [
                'name' => 'เสต็กสันในหมูพันเบคอน',
                'description' => 'เสต็ก_หมู_พันเบคอน',
                'image_url' => '/images/foods/fillet_mignon.png',
                'is_recommend' => 0,
                'price' => 149.00,
                'discount' => 0,
                'category_id' => 6,
            ],
            [
                'name' => 'สปาเก็ตตี้',
                'description' => 'สปาเก็ตตี้ซอสเนื้อ',
                'image_url' => '/images/foods/spaghetti_meatsauce.png',
                'is_recommend' => 0,
                'price' => 69.00,
                'discount' => 0,
                'category_id' => 7,
            ],
            [
                'name' => 'เพนเน่',
                'description' => 'เพนเน่ซอสเนื้อ',
                'image_url' => '/images/foods/penne_meatsauce.png',
                'is_recommend' => 0,
                'price' => 69.00,
                'discount' => 0,
                'category_id' => 7,
            ],
             [
                'name' => 'มันบด',
                'description' => 'มัน',
                'image_url' => '/images/foods/munbod.jpg',
                'is_recommend' => 1,
                'price' => 40.00,
                'discount' => 5,
                'category_id' => 9,
            ],
            [
                'name' => 'เสต็กหมู',
                'description' => 'หมู',
                'image_url' => '/images/foods/steakmoo.png',
                'is_recommend' => 1,
                'price' => 80.00,
                'discount' => 5,
                'category_id' => 8,
            ],
                       
            [
                'name' => 'เสต็กปลา',
                'description' => 'ปลา',
                'image_url' => '/images/foods/steakpla.png',
                'is_recommend' => 1,
                'price' => 80.00,
                'discount' => 5,
                'category_id' => 8,
            ],            
            [
                'name' => 'เสต็กไก่',
                'description' => 'ไก่',
                'image_url' => '/images/foods/steakkai.png',
                'is_recommend' => 1,
                'price' => 80.00,
                'discount' => 5,
                'category_id' => 8,
            ],
            [
                'name' => 'ต้มจืดหมู',
                'description' => 'หมู',
                'image_url' => '/images/foods/tomjuedmoo.png',
                'is_recommend' => 1,
                'price' => 60.00,
                'discount' => 5,
                'category_id' => 10,
            ],[
                'name' => 'หอมทอด',
                'description' => 'หัวหอม',
                'image_url' => '/images/foods/homtod.png',
                'is_recommend' => 1,
                'price' => 40.00,
                'discount' => 5,
                'category_id' => 9,
            ],[
                'name' => 'ทาโกะยากิ',
                'description' => 'รวมมิตร',
                'image_url' => '/images/foods/takoyaki.png',
                'is_recommend' => 1,
                'price' => 50.00,
                'discount' => 5,
                'category_id' => 9,
            ]
        ]);
    }
}